name: Deploy to EC2

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy:
    # Run the job only if the pull request is merged into the main branch
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    env:
      ECR_REGISTRY: 847776094262.dkr.ecr.ap-south-1.amazonaws.com
      EC2_USER: ubuntu
      EC2_HOST: 3.109.182.132
      SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      ENCODED_ENV_FILE: ${{ secrets.ENCODED_ENV_FILE }}
      AWS_REGION: ap-south-1

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose v2
      run: |
        DOCKER_COMPOSE_VERSION="v2.3.3"
        mkdir -p ~/.docker/cli-plugins/
        curl -SL https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
        chmod +x ~/.docker/cli-plugins/docker-compose
        docker compose version

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Decode .env file
      run: |
        echo "${{ env.ENCODED_ENV_FILE }}" | base64 --decode > .env

    - name: Log in to Amazon ECR
      id: login-ecr
      run: |
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

    - name: Build and push Docker image using Docker Compose
      run: |
        docker compose -f docker-compose.main.yml build
        docker compose -f docker-compose.main.yml push

    - name: Set up SSH key
      run: |
        echo "${{ env.SSH_KEY }}" > id_rsa
        chmod 600 id_rsa

    - name: Copy .env file to EC2
      run: |
        scp -i id_rsa -o StrictHostKeyChecking=no .env ${{ env.EC2_USER }}@${{ env.EC2_HOST }}:/home/ubuntu/eligibility-engine/frontend/.env

    - name: Copy docker-compose.main.yml file to EC2
      run: |
        scp -i id_rsa -o StrictHostKeyChecking=no docker-compose.main.yml ${{ env.EC2_USER }}@${{ env.EC2_HOST }}:/home/ubuntu/eligibility-engine/frontend/docker-compose.main.yml

    - name: SSH to EC2 and run Docker Compose
      run: |
        ssh -i id_rsa -o StrictHostKeyChecking=no ${{ env.EC2_USER }}@${{ env.EC2_HOST }} << 'EOF'
          cd /home/ubuntu/eligibility-engine/frontend
          aws ecr get-login-password --region ap-south-1  | docker login --username AWS --password-stdin 847776094262.dkr.ecr.ap-south-1.amazonaws.com
          docker compose -f docker-compose.main.yml pull
          docker compose -f docker-compose.main.yml up -d --no-build --force-recreate
